// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoMF1y6BDzqHbnU6N_uQzNMd5lbRzHT6w',
    appId: '1:1063295167692:web:d294da8f9f83e3029aa669',
    messagingSenderId: '1063295167692',
    projectId: 'ecommerce-mobile-195ff',
    authDomain: 'ecommerce-mobile-195ff.firebaseapp.com',
    databaseURL: 'https://ecommerce-mobile-195ff-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-mobile-195ff.appspot.com',
    measurementId: 'G-VWYTD0CQXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE56TSTHe3qnWkYv0cbyxi19_w14SH3qY',
    appId: '1:1063295167692:android:eaf0ca5b13bd3e719aa669',
    messagingSenderId: '1063295167692',
    projectId: 'ecommerce-mobile-195ff',
    databaseURL: 'https://ecommerce-mobile-195ff-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-mobile-195ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1wwM2svpCrZUT8Ys3_nANVu1xhBEky9A',
    appId: '1:1063295167692:ios:3914443ce5e20f419aa669',
    messagingSenderId: '1063295167692',
    projectId: 'ecommerce-mobile-195ff',
    databaseURL: 'https://ecommerce-mobile-195ff-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-mobile-195ff.appspot.com',
    androidClientId: '1063295167692-87sj7ed3kmvn9alsn7a68r374hlsr1ui.apps.googleusercontent.com',
    iosClientId: '1063295167692-799942kar6mr9du4h2ov292jrpiquqg5.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1wwM2svpCrZUT8Ys3_nANVu1xhBEky9A',
    appId: '1:1063295167692:ios:3914443ce5e20f419aa669',
    messagingSenderId: '1063295167692',
    projectId: 'ecommerce-mobile-195ff',
    databaseURL: 'https://ecommerce-mobile-195ff-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-mobile-195ff.appspot.com',
    androidClientId: '1063295167692-87sj7ed3kmvn9alsn7a68r374hlsr1ui.apps.googleusercontent.com',
    iosClientId: '1063295167692-799942kar6mr9du4h2ov292jrpiquqg5.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoMF1y6BDzqHbnU6N_uQzNMd5lbRzHT6w',
    appId: '1:1063295167692:web:f9ce5f8661823f599aa669',
    messagingSenderId: '1063295167692',
    projectId: 'ecommerce-mobile-195ff',
    authDomain: 'ecommerce-mobile-195ff.firebaseapp.com',
    databaseURL: 'https://ecommerce-mobile-195ff-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-mobile-195ff.appspot.com',
    measurementId: 'G-S0D869JVDR',
  );

}